2018-05-31 19:02:27 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:27 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:31 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:31 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:36 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:36 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:36 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:36 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:36 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:36 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:36 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:36 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:37 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:37 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:02:37 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:02:37 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:18 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:18 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:22 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:22 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:27 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:27 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:27 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:27 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:27 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:27 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:27 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:27 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:28 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:28 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:07:28 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:07:28 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:14:07 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:14:07 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:14:07 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:14:07 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:14:07 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:14:07 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:14:07 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:14:07 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:15:24 [exception ERROR] Internal Server Error: /assets/asset/slb/
Traceback (most recent call last):
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'assetslb-list' not found. 'assetslb-list' is not a valid view function or pattern name.
2018-05-31 19:19:55 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:19:55 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:19:58 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:19:58 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:05 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:05 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:05 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:05 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:49 [exception ERROR] Internal Server Error: /assets/asset/slb/
Traceback (most recent call last):
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/middleware/locale.py", line 24, in process_request
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/xiaoma/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/xiaoma/PycharmProjects/easemob-ops/ops_billing/apps/jumpserver/urls.py", line 28, in <module>
    url(r'^api/assets/', include('assets.urls.api_urls', namespace='api-assets')),
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/xiaoma/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/xiaoma/PycharmProjects/easemob-ops/ops_billing/apps/assets/urls/api_urls.py", line 28, in <module>
    api.AssetSlbViewSet.as_view(), name='assetslb-info'),
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/rest_framework/viewsets.py", line 55, in as_view
    raise TypeError("The `actions` argument must be provided when "
TypeError: The `actions` argument must be provided when calling `.as_view()` on a ViewSet. For example `.as_view({'get': 'list'})`
2018-05-31 19:20:57 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:57 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:20:59 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:20:59 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:21:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:21:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:21:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:21:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:21:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:21:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:21:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:21:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:21:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:21:04 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:21:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:21:04 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:36 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:36 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:40 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:40 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:46 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:46 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:46 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:46 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:46 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:47 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:47 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:47 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:47 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:47 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:47 [signals_handler DEBUG] Receive django ready signal
2018-05-31 19:22:47 [signals_handler DEBUG]   - fresh all settings
2018-05-31 19:22:48 [exception ERROR] Internal Server Error: /assets/asset/slb/
Traceback (most recent call last):
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/xiaoma/pyenv/jumpserver/lib/python3.6/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'assetslb-info' not found. 'assetslb-info' is not a valid view function or pattern name.
2018-05-31 19:37:46 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-31 19:37:46 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-31 19:37:46 [tasks DEBUG] Period task disabled, test admin user connectability pass
